### ISSUE TITLE
Microsoft Outlook A Stable Connection to the Server Cannot be Established

### ISSUE THREAD

**Issue by aperry39** [MailCore/mailcore2#1652] opened 2017-07-28 16:26 UTC
Hey! I am working in Swift 3 and XCode 8. I can't seem to get my connection to work. I keep getting this:
`2017-07-28 12:16:00.312355-0400 FeedbackApplication[55340:1250201] [] __nw_connection_get_connected_socket_block_invoke 1 Connection has no connected handler
2017-07-28 12:16:00.313039-0400 FeedbackApplication[55340:1250174] Error sending email: Optional(Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.})`

Here is my code:

        let smtpSession = MCOSMTPSession()
        smtpSession.hostname = "smtp-mail.outlook.com"
        smtpSession.username = "Name@capitalone.com"
        smtpSession.password = nil
        smtpSession.port = 25
        smtpSession.authType = MCOAuthType.xoAuth2Outlook
        smtpSession.connectionType = MCOConnectionType.startTLS
        smtpSession.connectionLogger = {(connectionID, type, data) in
            if data != nil {
                if let string = NSString(data: data!, encoding: String.Encoding.utf8.rawValue){
                    NSLog("Connectionlogger: \(string)")
                }
            }
        }
        let builder = MCOMessageBuilder()
        builder.header.to = [MCOAddress(displayName: "My Work", mailbox: "Name@capitalone.com")]
        builder.header.from = MCOAddress(displayName: "My Work", mailbox: "Name@capitalone.com")
        builder.header.subject = "My message"
        builder.htmlBody = "Yo myself, this is a test message!"
        let rfc822Data = builder.data()
        let sendOperation = smtpSession.sendOperation(with: rfc822Data)
        sendOperation?.start { (error) -> Void in
            if (error != nil) {
                NSLog("Error sending email: \(String(describing: error))")
            } else {
                NSLog("Successfully sent email!")
            }
        }

Does anyone know what I am doing wrong.

**Comment by NSDeveloper** [comment] 2017-08-07 09:51
Use 587 instead of 25 ?

**Comment by xtation** [comment] 2018-01-08 20:50
after setting port to 587 it still give error 
 "A stable connection to the server could not be established."

**Comment by xtation** [comment] 2018-01-24 21:36
i am going with this issue to now i can send email from outlook using autetype
 let smtpSession = MCOSMTPSession()
                smtpSession.hostname = "smtp-mail.outlook.com"
                smtpSession.username = "**********8@outlook.com"
                smtpSession.password = "*********"
                smtpSession.port = 587
                smtpSession.authType = MCOAuthType.saslLogin
                smtpSession.connectionType = MCOConnectionType.startTLS

**Comment by beczesz** [comment] 2018-05-14 07:45
Hi there, 
I tried it on Android without any luck with the same configuration

```
 SMTPSession smtpSession = new SMTPSession();
        smtpSession.setHostname("smtp-mail.outlook.com");
        smtpSession.setPort(587); // I trued 25 as well
        smtpSession.setUsername([correct username]);
        smtpSession.setPassword([Corect password]);
        smtpSession.setConnectionType(ConnectionType.ConnectionTypeStartTLS);
        smtpSession.setAuthType(AuthType.AuthTypeSASLLogin);
```

The IMAP operations are working fine though.

**Comment by monicager** [comment] 2018-07-18 20:51
Hello, I'm having this same issue, have you been able to solve?

**Comment by xtation** [comment] 2018-07-24 10:18
change authtype what i mean to say check every authtype to send email

**Comment by xtation** [comment] 2018-07-24 10:19
let smtpSession = MCOSMTPSession()
smtpSession.hostname = "smtp-mail.outlook.com"
smtpSession.username = "*
*@outlook.com <8@outlook.com>"smtpSession.password = "*"
smtpSession.port = 587
smtpSession.authType = MCOAuthType.saslLogin
smtpSession.connectionType = MCOConnectionType.startTLS

**Comment by beczesz** [comment] 2018-07-24 11:08
well I tried with both Auth2 and Password without any luck. And every possible combination. The problem is only on Android.

**Comment by xtation** [comment] 2018-07-25 21:29
i dont know about andoid this work for me on ios :)

**Comment by vymallesh** [comment] 2019-05-30 06:48
Hello there, i am not able to receive mails in Outlook.Below is the configuration which i made,

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.outlook.com";
    session.username = @"Dummmy@outlook.com";
    session.password = nil;
    session.port = 993;
    session.authType = MCOAuthTypeSASLLogin;
    session.OAuth2Token = accessToken;
    session.connectionType = MCOConnectionTypeTLS;
    session.checkCertificateEnabled = false;

Here i tried by sending the password too, but no luck.Sending password as 'nil' as i am sending the access token.

I am getting below error, 

Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

I am not getting the exact issue.

**Comment by vymallesh** [comment] 2019-05-30 09:25
@xtation ,

What is the Imap configuration for Outlook, i was using below code.But i am getting below error.

Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.

//Imap Configuration which i am doing

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.outlook.com";
    session.username = @"dummy@outlook.com";
    session.password = nil;
    session.port = 993;
    session.authType = MCOAuthTypeSASLLogin;
    session.OAuth2Token = accessToken;
    session.connectionType = MCOConnectionTypeStartTLS;
    session.checkCertificateEnabled = false;


I was looking into this issue since a week, but no luck.Kindly let me know what are the changes to be done in above settings.

**Comment by xtation** [comment] 2019-05-30 09:29
Email me ur problem bro on this mail farhan.ahmed22999@gmail.com

**Comment by vymallesh** [comment] 2019-05-30 09:53
@xtation ,

sent you email.Please check

**Comment by vymallesh** [comment] 2019-05-31 12:01
@xtation , 

Can i please know an update on my issue ?

**Comment by xtation** [comment] 2019-06-01 09:55
MinI-Outlook.zip
<https://drive.google.com/file/d/1we5UnC9s387WBOdAYLoxPZvOEsvBz74B/view?usp=drive_web>

**Comment by haithngn** [comment] 2019-06-03 08:20
any update ?
p/s: if you guy are using Outlook Oauth token please show us your scopes

**Comment by haithngn** [comment] 2019-06-03 13:54
so can we close this issue now ?

**Comment by vymallesh** [comment] 2019-06-03 13:56
Yes,Thanks for your time !!
If i have any doubts further, will let you know.

**Closed** 2019-06-03 13:57 UTC

**Comment by Be-Maps** [comment] 2024-08-29 10:23
Opened a new ticket for it:
https://github.com/MailCore/mailcore2/issues/2007

The above people end up using outlook without OAuth, but soon (this September) it will be mandatory:
https://support.microsoft.com/en-gb/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d 

I am getting the below error:
2024-08-29 09:32:22 SettingsDialog :  : acquireTokenSilently: Access token expiery is: 2024-08-29 10:32:22
2024-08-29 09:32:22 SettingsDialog :  : acquireTokenSilently: Refreshed Access token is: EwCYA8l6BAAUbDba3x2OMJElkF7gJ4z/VbCPEz0AARR7frPnZGsM8SaVqr6yJ2Cp/t/ZppviKuQFzopp2OCTA+k4CTgbBc5gjbXjYrpAGSMZhibBmnIKu0zgW+kgsPOMZZ2451HpGOlYMhjIXNYP1HB7prux6o53bNu9j4MdXFww9rwXKxja0q1rPxkZCak1ZUyLwd1rNVU7Dzt1uGbnAR5qYqP08KV18n3MmyfuXKhpV8T7BPC2HEm7LzTd2zMh6YesGWV8jA1IPR8i+frDwwv1FtAR95wMtmMyi8+6BjirFYLNTgPZh7/k8rMX33t/rUwaxt0N4F9AenD7gICrTzdwWgXenNCdjeQO0T2Obu8tnE5rm0LzGmBsBlEYcS0QZgAAECNeD+H8O1h//7/Omj3eOM5gAj96OFnuKPkhZw7pCHzqzR0wLNLkNDv7/NFMaUXD4f3RwlE1i43SXOIzHYJ2/D0iJAiGPEWTrD5ArohJ3bHCsTVpCE1NYC8Wo0hOKWeq7OHfy/b0ou8o757mnCfMigJsPOQzDsuF+H7HgHQx/E4/6swfdWRrPqviRjeUpo0b7834CRe8h4eZhPuonPOBakg8NMTQkA+AHGYqUNAEJuJjdttOtUhrik65xEpOpdKl8Q5Tz9MQrZmN26sF1XG6CsBL1GCB/2qpLMa4VVvWKHJWk5mQZBjlDbTNxtPfm2Pnx4tZ2bleQwHlBf2sMnsjCecpDAPAHJLp8Bl05dGj5WL3TaKZGiQjuHPtGYYHs1LMn9VPyb+dDcfuKuwjMw5jPEuDNtLhTet73N07HVT0ebHrU7jg9GJwYkR1d7th0LuGv0h1NHZ8fKbSdnqvQhPMnGmGBD+O5Lil+tdwitpPL7VoR//W9exG/CMrDKYd3WS5QxRlMBz2zwUaPyRidLFEtJLQPbHG4wJYwOd7biIrESq09Cdq7uKLwokq9a7ItAIq0sKbfainBL+QCos60kHu+QGEpIR/lfnyNunewtAAIc/+YFALymXcUGE8uiDj+97X/URnXGvphDD5hrsSdg86Cuj+Kk4vf/tpTnR5KYk1j/DpBYSMKspCND0rTT5iNkm3L8C/9nBW5ix7Qmm5y+vlnhdU/Tzt9yXsN3d9uUjezMV6vR5flDVfJuIsitqOdvAPGOi523vgtQtIZoUgP/xDRb58Vmd3rrjBkg+BqwjGKAvdBnT/4op2hkdKLc3CTMU/T2ZWpAI=
2024-08-29 09:32:22 SettingsDialog :  :  ... tasks started ------------>>   EXECUTE OUTLOOK TEST 
2024-08-29 09:32:23 : imapConnect - IMAP Connect Error: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}
