### ISSUE TITLE
Android dies when IMAPFolderInfoOperation is started

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1253] opened 2015-10-14 07:02 UTC
data/dalvik-cache/arm/system@framework@boot.oat (???)
  at com.libmailcore.IMAPSession.folderInfoOperation(Native method)

**Comment by dinhviethoa** [comment] 2015-11-06 17:30
close as duplicate of #1257.

**Closed by dinhviethoa** 2015-11-06 17:30 UTC
