### ISSUE TITLE
Swift3 

### ISSUE THREAD

**Issue by Lutzmann** [MailCore/mailcore2#1519] opened 2016-09-27 17:38 UTC
I work with Swift 3 and Xcode 8 and i have  this Issue:
linker command failed with exit code 1 (use -v to see invocation)

With Xcode 7.3 it was running with no Problems ?!

**Comment by Lutzmann** [comment] 2016-10-03 07:44
Who can help ? I can not compile my program. I have to make major changes in my program, but it is not possible to compile!

Lutz

**Comment by hankinsoft** [comment] 2016-10-03 12:13
I think this is a duplicate of #1511

**Comment by dinhviethoa** [comment] 2016-10-04 00:20
Apple made some major changes in Swift 3.0
It's not an issue with MailCore.

**Closed by dinhviethoa** 2016-10-04 00:20 UTC
