### ISSUE TITLE
2:18.802 EveryPod[45737:1084569] Error sending email: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials.

### ISSUE THREAD

**Issue by Zaheer6110** [MailCore/mailcore2#1380] opened 2016-03-15 11:20 UTC
Connection Logger says..
Response shows Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257
tried everything changed ports run on different devices but still getting same issue..
I dont know why this error is occurring and why it saying about username and password because im using outh2 where password is not even required.. i also tried using password=nil as well. without outh2 it works but with access token its not working.. When i cahnage authentication type to MCOAuthTypeSASLPlain and gave username and password its working well but not without them.. please Help me im struggling from last 3,4 days
  
    MCOSMTPSession * smtpSession = [[MCOSMTPSession alloc] init];
    smtpSession.hostname = @"smtp.gmail.com";
    smtpSession.port = 465;
smtpSession.username = user; //saved value
smtpSession.connectionType = MCOConnectionTypeTLS;
smtpSession.OAuth2Token = token; //saved value(Validated)
   smtpSession.authType = MCOAuthTypeXOAuth2;
   smtpSession.checkCertificateEnabled=NO;

    
    
    MCOMessageBuilder * builder = [[MCOMessageBuilder alloc] init];
    MCOAddress *fromAdress=[[MCOAddress alloc]init];
    fromAdress = [MCOAddress addressWithMailbox:user];
    MCOAddress *toAdress=[[MCOAddress alloc]init];
    toAdress = [MCOAddress addressWithMailbox:self.to.text];
    [[builder header] setFrom:fromAdress];
    [[builder header] setTo:@[toAdress]];
    NSString *htmlbody1=@"Body";
 [[builder header] setSubject:@"Some_subject"];
    [builder setHTMLBody:htmlbody1];
     [smtpSession setConnectionLogger:^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        NSString *response = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        NSLog(@"Response %@",response);
    }];
    NSData * rfc822Data = [builder data];
    
    MCOSMTPSendOperation *sendOperation = [smtpSession sendOperationWithData:rfc822Data];
    [sendOperation start:^(NSError *error) {
        if(error) {
      
            NSLog(@"Error sending email: %@", error);
        } else {
           
        }
    }];

**Comment by Zaheer6110** [comment] 2016-03-15 11:22
then referneced page is 2 step verification.. i know its not issue about password.. Im just missing something

**Comment by Zaheer6110** [comment] 2016-03-16 06:20
@dinhviethoa Help needed..

**Comment by dinhviethoa** [comment] 2016-03-16 06:22
Please refer to https://developers.google.com/gmail/xoauth2_protocol

**Comment by Zaheer6110** [comment] 2016-03-16 06:25
I have read it carefully but still not finding the exact error

**Comment by Zaheer6110** [comment] 2016-03-16 06:26
I dont know where im sending empty response..

**Comment by Zaheer6110** [comment] 2016-03-16 06:27
@dinhviethoa Im getting this error from last two days.. and The client sends an empty response ("\r\n") to the challenge containing the error message. i dont know where im sending empty response.

**Comment by Zaheer6110** [comment] 2016-03-16 06:44
@dinhviethoa  tell me what im missing here?? because it work fine with password with SASPlain but not in case of token

**Comment by Zaheer6110** [comment] 2016-03-17 09:43
@dinhviethoa ??

**Comment by dinhviethoa** [comment] 2016-03-18 05:04
You can use connectionLogger to debug your issue.

**Comment by Zaheer6110** [comment] 2016-03-18 05:34
Yes I have used connection logger. and Connection logger was saying Username and Password not accepted but im not giving password im using outh2

**Comment by Zaheer6110** [comment] 2016-03-21 15:32
@dinhviethoa  it look like i am sending empty response somewhere but still cant figure out what im missing. i have checked my access tokens always using https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=
no issue with token then what im missing @dinhviethoa

**Comment by Zaheer6110** [comment] 2016-03-21 15:33
Tell me if you have any idea because struggling from last week and its pretty simple but im missing simple line

**Comment by Zaheer6110** [comment] 2016-03-21 15:34
I have tried everything. and follow all the instructions in previous threads. I have allowed less secure apps unlock captche etc but still getting same error

**Comment by Zaheer6110** [comment] 2016-03-21 15:34
I need some help from you @dinhviethoa

**Comment by Zaheer6110** [comment] 2016-03-21 15:37
here is response that i am getting
2016-03-21 20:35:57.940 EveryPod[447:65229] Response EHLO Tester-iPhone

2016-03-21 20:35:58.139 EveryPod[447:65229] Response 250-smtp.gmail.com at your service, [103.255.6.102]

250-SIZE 35882577

250-8BITMIME

250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH

250-ENHANCEDSTATUSCODES

250-PIPELINING

250-CHUNKING

250 SMTPUTF8

2016-03-21 20:35:58.141 EveryPod[447:65229] Response AUTH XOAUTH2 
2016-03-21 20:35:58.142 EveryPod[447:65229] Response dXNlcj16YWhlZXI2MTEwQGdtYWlsLmNvbQFhdXRoPUJlYXJlciB5YTI5LnJBSW5INFNwQXFEdlBMblh4dXBsZll0d3VTYk53TElmd1djdHZvblRDNGNqQW5JSWhsZS1wc0VwendPS3kyWmVudwEB
2016-03-21 20:35:58.142 EveryPod[447:65229] Response 

2016-03-21 20:35:58.747 EveryPod[447:65229] Response 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==

2016-03-21 20:35:58.747 EveryPod[447:65229] Response 

2016-03-21 20:35:59.053 EveryPod[447:65229] Response 535-5.7.8 Username and Password not accepted. Learn more at

535 5.7.8  https://support.google.com/mail/answer/14257 w133sm12979070wmd.3 - gsmtp

2016-03-21 20:35:59.116 EveryPod[447:65088] Error sending email: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

**Comment by Zaheer6110** [comment] 2016-03-21 15:42
and problem is token expires after 3600 seconds then need to refresh it. but if token expires and token becomes invalid i have tried to check what would be the error after expiration it still giving me same error. Are there issues with token also??

**Comment by Zaheer6110** [comment] 2016-03-21 15:43
I m missing some basic thing here. Guide me @dinhviethoa

**Comment by dinhviethoa** [comment] 2016-03-21 16:02
There an example with IMAP about how to generate the oauth2 token.
Please take a look to see how it's different from what you're doing.

**Comment by Zaheer6110** [comment] 2016-03-22 05:33
I have tried IMAP also

**Comment by Zaheer6110** [comment] 2016-03-22 05:50
Getting the same response @dinhviethoa

**Comment by Zaheer6110** [comment] 2016-03-22 06:54
i have tried everything you have mentioned in mailcore but still getting the same error @dinhviethoa

**Comment by dinhviethoa** [comment] 2016-03-22 15:16
Have you tried to sample code in mailcore2/example?

**Comment by lksnmnn** [comment] 2016-03-25 17:56
Dear @Zaheer6110 please compare your code to MailCores example project. The issue is not with MailCore here but somehow with your code. 

The example project shows a working (!) example for using OAuth. Google even has its own framework for Mac and iOS to get **valid** OAuth tokens. Maybe this helps you https://github.com/google/gtm-oauth

**Comment by Zaheer6110** [comment] 2016-03-30 08:03
@iksnmnn i am getting OAuth token and i have check the validity of tokens using
https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=
but still getting error in sending mail. dont know why.

**Comment by lksnmnn** [comment] 2016-03-30 08:29
If your code uses MailCore as it does in the example project it should work. Can you receive emails?

Maybe you do not have all the correct permissions for sending an email. We use _https://mail.google.com_ as ```scope``` when requesting access via OAuth.

**Comment by Zaheer6110** [comment] 2016-04-02 10:01
Thanks @Iksnmnn @dinhviethoa now i solved that issue. actually problem was with my gmail account

**Comment by lksnmnn** [comment] 2016-04-02 10:04
Please close this issue

**Closed** 2016-04-02 11:13 UTC
