### ISSUE TITLE
Adding MailCore2 via CocoaPods as a framework / Swift support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [MailCore/mailcore2#1268] opened 2015-11-09 10:21 UTC
I'm trying to add MailCore2 via CocoaPods to my Swift project. Here's my `Podfile`.
```
platform :ios, '8.0'
use_frameworks!

pod 'mailcore2-ios'
```
Notice that I have the `use_frameworks!` flag added which converts it to a framework.

The pod installation is successful. No build errors. But then when I try to `import MailCore` in the view controllers, I get a **No such module** error.

What am I missing here? Am I using a wrong module name?

**Comment by dinhviethoa** [comment] 2015-11-10 01:06
I don't really know how use_frameworks works with Cocoapods.

**Comment by keith** [comment] 2015-11-21 23:31
You should try importing mailcore in your bridging header instead.

**Comment by Isuru-Nanayakkara** [comment] 2015-11-22 04:57
@keith Yes, I tried that and it works. Problem is I have couple of pods (Alamofire, SwiftyJSON) which are purely Swift so they can't be installed along with other pods written in Objective-C since they require the `use_frameworks!` flag.

**Comment by SAPessi** [comment] 2015-12-29 00:54
+1

**Comment by SAPessi** [comment] 2015-12-29 01:18
Just after I added the +1 I found a solution (although it's a pain in the neck and hopefully it will be resolved in a future release). CocoaPods creates a .a library file for the project when used with the use_frameworks! option, but it also downloads all of the headers. You can reference the library from the headers:
1. In your project build settings, change the "User Header Search Paths" and add the Pods folder as recursive ```Pods/**``` for both debug and release
2. Crete a bridging header file (just a new .h file) in your project and reference the MailCore.h file from there. In my case, ```#import <MailCore/MailCore.h>```
3. Back to your project build settings, in the Swift Compiler - Code Generation section look for the Objective-C Bridging Header value and set it to the path to your bridging header. In my case, ```ProjectName/<ProjectName>-Bridging-Header.h```

This did the trick for me.

**Comment by benjaminhorner** [comment] 2016-01-15 13:16
@SAPessi: Could you please give more details?
I tried your solution but it isn't working. 
NB: The headers are not being imported in my Project. All I get is the .a file…

**Comment by SAPessi** [comment] 2016-01-15 17:56
Did you create the bridging header?
1. Create a new Objective-C header file called YourProjectName-Brdiging-Header.h
2. Import the MailCore headers in this file:
    
    #ifndef YourProject_Bridging_Header_h
    #define YourProject_Bridging_Header_h

    #import <MailCore/MailCore.h>
    #import <MailCore/MCOConstants.h>

    #endif /* YourProject_Bridging_Header_h */

3. Next, go to the project build settings and look for this section:
Swift Compiler - Code Generation
  > Objective-C Bridging Header

and add the name of your bridging header to both the Debug and Release configurations. In my case this was "YourProjectName/ProjectName-Bridging-Header.h".

You should now have access to the MailCore objects:

    let session = MCOIMAPSession()
    session.hostname = "imap.gmail.com"
    session.port = 993
    session.username = // username
    session.password = // password
    session.connectionType = MCOConnectionType.TLS
    let uidSet = MCOIndexSet(range: MCORange(location: 1, length: UINT64_MAX))//[MCOIndexSet indexSetWithRange:MCORangeMake(1,UINT64_MAX)];
    let fetchOp = session.fetchMessagesByUIDOperationWithFolder("INBOX", requestKind: MCOIMAPMessagesRequestKind.Headers, uids: uidSet)
        
    fetchOp.start { (err, msg, vanished) -> Void in
        print("error from server \(err)")
        print("fetched \(msg?.count) messages")
    }

**Comment by dinhviethoa** [comment] 2016-01-15 22:03
Is there something that I can make it easier in MailCore to use it in Swift?

**Comment by SAPessi** [comment] 2016-01-15 22:25
I see that you can already product a dynamic framework from the project, you should use the framework in your pod specs - see here: https://blog.cocoapods.org/CocoaPods-0.36/

**Comment by brandonshin** [comment] 2016-01-18 08:08
+1 💌

**Comment by benjaminhorner** [comment] 2016-01-18 22:20
@SAPessi : yes I have a bridging header and it is working for all my other Obj-C dependencies but not for mailcore.

Of course I know I shouldn't have to do this but I still tried (just in case) adding import MailCore for which of course I get an error.

However, for all the other mailcore types I also get errors. Type doesn't exist.

Maybe I should say I am also using frameworks…

**Comment by SAPessi** [comment] 2016-01-18 23:21
@benjaminhorner can you share some screenshots of your Xcode setup, specifically the header search path and Bridging header search path? Also, can you post the code of your bridging header?

**Comment by dinhviethoa** [comment] 2016-02-01 15:24
An update here: I haven't been able to build mailcore2 as a framework from the command line (See build-mailcore2-framework-ios.sh).
It will fail requiring a signature for the target.

**Comment by merrickluo** [comment] 2016-04-19 10:37
Try this http://stackoverflow.com/questions/29836356/ios8-dynamic-frameworks-codesign-error-code-signing-is-required-for-product 

select "none" team on mailcore ios target, I tried it works in build-mac/mailcore2.xcodeproj.

**Comment by merrickluo** [comment] 2016-04-21 10:05
I managed to make build-mailcore2-framework-ios.sh build without error with the method above, but MailCore.framework are not created.

```
** BUILD SUCCEEDED ** (65147 ms)

finished
/Users/merrick/Developer/iOS/yoc-mailcore2/scripts/include.sh/build-dep.sh: line 93: cd: /Users/merrick/MailCore-Builds/dependencies/workdir/20160421174316/tmp/bin/Release: No such file or directory

zip error: Nothing to do! (try: zip -qry /Users/merrick/MailCore-Builds/dependencies/builds/mailcore2-framework-ios/mailcore2-framework-ios-2.zip . -i MailCore.framework)
build of mailcore2-framework-ios-2 done
```

**Comment by dinhviethoa** [comment] 2016-04-21 17:17
I think I know what the issue is:
- We probably need to build two different frameworks when it's for iOS: for device and for simulator.
- We'll produce one build containing both frameworks.

Could you try the following and submit a pull request if it works?
Thanks!

line 92:

You need to duplicate those lines:
```
    cd "$tmpdir/bin/Release"
    defaults write "$tmpdir/bin/Release/$library/Resources/Info.plist" "git-rev" "$rev"
    mkdir -p "$resultdir/$name"
    zip -qry "$resultdir/$name/$name-$version.zip" "$library"
```

to something like that:

```
    defaults write "$tmpdir/bin/Release-iphonesimulator/$library/Resources/Info.plist" "git-rev" "$rev"
    defaults write "$tmpdir/bin/Release-iphoneos/$library/Resources/Info.plist" "git-rev" "$rev"
    mv "$tmpdir/bin/Release-iphonesimulator" "$tmpdir/bin/iphonesimulator"
    mv "$tmpdir/bin/Release-iphoneos" "$tmpdir/bin/iphoneos"
    mkdir -p "$resultdir/$name"
    cd "$tmpdir/bin"
    zip -qry "$resultdir/$name/$name-$version.zip" "iphoneos/$library" "iphonesimulator/$library"
```

**Comment by merrickluo** [comment] 2016-04-22 08:12
It's working now, but when I use the built framework in my project, it still failed with an codesign error.

    MailCore.framework: code object is not signed at all

**Comment by dinhviethoa** [comment] 2016-05-12 06:12
@merrickluo Have you been able to fix it?

**Comment by merrickluo** [comment] 2016-05-13 02:06
@dinhviethoa Nope, don't know much about Xcode code sign. I am using Carthage to compile mailcore2 now, and works fine.

**Closed** 2016-05-13 05:04 UTC
