### ISSUE TITLE
[Bug] - Plans for Apple's M1 Architecture Support?

### ISSUE THREAD

**Issue by vinhqn** [MailCore/mailcore2#1941] opened 2022-04-14 09:30 UTC
Dear @dinhvh 

I have problem building mailcore2 on Apple's M1 Architecture, can mailcore2 update to support Apple's M1 Architecture?

ld: in /Users/vinhnguyen/whpmail/Pods/mailcore2-ios/lib/libMailCore-ios.a(MCONNTPFetchOverviewOperation.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/vinhnguyen/whpmail/Pods/mailcore2-ios/lib/libMailCore-ios.a' for architecture arm64

image : https://drive.google.com/file/d/1YzlMP01c4wvqagbd3y-SKmG-it24uW38/view?usp=sharing

**Comment by crasholo** [comment] 2022-04-26 09:46
+1 for this. I had to turn off mailcore2 usage from my iOS projects (without Rosetta support). 
I hope to have news soon. 
Thanks

**Comment by pedrosakey** [comment] 2022-05-15 12:18
🔝 hello same issue here, would it be possible to give an estimation about when it could be ready or should I try an alternative solution? 
Many thanks 🙏

**Comment by dinhvh** [comment] 2022-05-15 17:58
I'll find some time to get the dependencies built.

The issue is that we need to build the dependencies for arm64.

**Comment by kyungkoo** [comment] 2022-05-19 06:45
#1938

**Comment by dinhvh** [comment] 2022-07-25 14:39
Could you try with the latest master?
The build should be fixed now.

**Closed by dinhvh** 2022-07-25 14:39 UTC
Labels: bug

**Comment by dan-ryan** [comment] 2022-10-06 04:46
@dinhvh 
The Master branch doesn't work for me: https://ibb.co/Sy1Z62Z

**Comment by mpdifran** [comment] 2023-03-05 02:30
Yeah `master` doesn't work for me either on macOS or simulator.

**Comment by TXB444** [comment] 2024-07-01 11:23
Are there any plans of getting this working anytime soon?

**Comment by vikdenic** [comment] 2025-10-07 14:43
Did anyone ever find a MailCore solution that builds for Arm64 / doesn't require Rosetta?
