### ISSUE TITLE
crash on android 6.0

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1252] opened 2015-10-14 04:06 UTC
when I use the mailcore2 on android 6.o ,it crash

**Comment by dinhviethoa** [comment] 2015-10-14 04:39
Could you let me know what crashes?
I uploaded a new build for Android 16. Could you let me know if it works for you?

**Comment by githupfisher** [comment] 2015-10-14 06:07
when I use the Android 16 ,it can't works.

 native: #21 pc 007702a1  /data/dalvik-cache/arm/system@framework@boot.oat (???)

**Comment by dinhviethoa** [comment] 2015-10-14 06:18
Did you download the latest build? Could you let me know what doesn't work?

**Comment by githupfisher** [comment] 2015-10-14 06:25
yes,I download the latest build,but it crash when I use session.fetchAllFoldersOperation

 JNI DETECTED ERROR IN APPLICATION: expected a constructor but void com.libmailcore.NativeObject.initWithNative(long): 0x9e170fd8
10-14 02:15:11.529 28350-28350/im.mera.mera_android A/art: art/runtime/java_vm_ext.cc:410]     in call to NewObjectV
10-14 02:15:11.529 28350-28350/im.mera.mera_android A/art: art/runtime/java_vm_ext.cc:410]     from com.libmailcore.IMAPFetchFoldersOperation com.libmailcore.IMAPSession.fetchAllFoldersOperation()

**Comment by dinhviethoa** [comment] 2015-11-06 17:30
Could you try this build?
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-2.aar
Thanks!

**Comment by dinhviethoa** [comment] 2015-11-06 17:30
close as duplicate of #1257.

**Closed by dinhviethoa** 2015-11-06 17:30 UTC

**Comment by arunvijay88** [comment] 2015-12-10 12:22
how to make it work from Android 14
